version: "3.8"

services:
  fastapi:
    ports:
      - "8000:80"
    restart: on-failure
    networks:
      - default
      - redmine
    environment:
      - MONGODB_URL=mongodb://api_user:password123@mongo/api?retryWrites=true&w=majority
  mongo:
    image: "bitnami/mongodb:4.2" 
    environment:
      - MONGODB_USERNAME=api_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=api
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-data:/bitnami/mongodb
    restart: on-failure
    networks:
      - default

networks:
  redmine:
    external: true
    name: dss-pnrp-redmine-plugin_default

volumes:
  mongo-data:
